-- Run this on existing projects that already created base tables.

alter table if exists public.wardrobe_items
  add column if not exists is_favorite boolean not null default false;

alter table if exists public.history_entries
  add column if not exists is_favorite boolean not null default false;

create table if not exists public.app_logs (
  id bigint generated by default as identity primary key,
  code text not null,
  message text not null,
  meta jsonb not null default '{}'::jsonb,
  user_agent text,
  created_at_client timestamptz,
  created_at timestamptz not null default now()
);

alter table public.app_logs enable row level security;

drop policy if exists logs_anon_insert on public.app_logs;
create policy logs_anon_insert
on public.app_logs
for insert
to anon
with check (true);

drop policy if exists logs_anon_select on public.app_logs;
create policy logs_anon_select
on public.app_logs
for select
to anon
using (true);

grant select, insert on public.app_logs to anon;
